// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq7s_7Rnm73XHKiVRzRWzGKV52waKHf9Q',
    appId: '1:427298550927:web:3773c5b1bdba912ffaecfa',
    messagingSenderId: '427298550927',
    projectId: 'bookstore-5e53b',
    authDomain: 'bookstore-5e53b.firebaseapp.com',
    databaseURL: 'https://bookstore-5e53b-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-5e53b.appspot.com',
    measurementId: 'G-MENZKJ5YSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_hTVnKvyWI27sjM7k_ZCiWSoDQX_ttI',
    appId: '1:427298550927:android:6a2d253afef47b82faecfa',
    messagingSenderId: '427298550927',
    projectId: 'bookstore-5e53b',
    databaseURL: 'https://bookstore-5e53b-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-5e53b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFaebhqZEwdNVRY7C179fTLfGtPvhSQX8',
    appId: '1:427298550927:ios:02fc1313c1a093b6faecfa',
    messagingSenderId: '427298550927',
    projectId: 'bookstore-5e53b',
    databaseURL: 'https://bookstore-5e53b-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-5e53b.appspot.com',
    iosBundleId: 'com.example.mobileAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFaebhqZEwdNVRY7C179fTLfGtPvhSQX8',
    appId: '1:427298550927:ios:02fc1313c1a093b6faecfa',
    messagingSenderId: '427298550927',
    projectId: 'bookstore-5e53b',
    databaseURL: 'https://bookstore-5e53b-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-5e53b.appspot.com',
    iosBundleId: 'com.example.mobileAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq7s_7Rnm73XHKiVRzRWzGKV52waKHf9Q',
    appId: '1:427298550927:web:285ca3efbf431119faecfa',
    messagingSenderId: '427298550927',
    projectId: 'bookstore-5e53b',
    authDomain: 'bookstore-5e53b.firebaseapp.com',
    databaseURL: 'https://bookstore-5e53b-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-5e53b.appspot.com',
    measurementId: 'G-8LX5P0QBLG',
  );

}